- README.md
- libs/infinity_emb/README.md
- libs/infinity_emb/infinity_emb/inference/batch_handler.py
- libs/infinity_emb/infinity_emb/inference/select_model.py
- libs/infinity_emb/infinity_emb/transformer/acceleration.py
- libs/infinity_emb/infinity_emb/transformer/classifier/torch.py
- libs/infinity_emb/infinity_emb/transformer/crossencoder/torch.py
- libs/infinity_emb/infinity_emb/transformer/embedder/sentence_transformer.py
> make fp16 default and add bettertransformer

- README.md
> update dstack support

- .github/workflows/linting.yaml
- .github/workflows/test.yaml
- libs/infinity_emb/infinity_emb/engine.py
- libs/infinity_emb/infinity_emb/inference/select_model.py
- libs/infinity_emb/infinity_emb/infinity_server.py
- libs/infinity_emb/infinity_emb/transformer/classifier/torch.py
- libs/infinity_emb/infinity_emb/transformer/crossencoder/torch.py
- libs/infinity_emb/infinity_emb/transformer/embedder/fastembed.py
- libs/infinity_emb/tests/unit_test/test_engine.py
> adding revision

- libs/infinity_emb/infinity_emb/infinity_server.py
> fix: cli start

- libs/infinity_emb/infinity_emb/args.py
- libs/infinity_emb/infinity_emb/engine.py
- libs/infinity_emb/infinity_emb/fastapi_schemas/pymodels.py
- libs/infinity_emb/infinity_emb/inference/caching_layer.py
- libs/infinity_emb/infinity_emb/inference/select_model.py
- libs/infinity_emb/infinity_emb/infinity_server.py
- libs/infinity_emb/infinity_emb/primitives.py
- libs/infinity_emb/infinity_emb/transformer/classifier/torch.py
- libs/infinity_emb/infinity_emb/transformer/crossencoder/optimum.py
- libs/infinity_emb/infinity_emb/transformer/crossencoder/torch.py
- libs/infinity_emb/infinity_emb/transformer/embedder/dummytransformer.py
- libs/infinity_emb/infinity_emb/transformer/embedder/fastembed.py
- libs/infinity_emb/infinity_emb/transformer/embedder/optimum.py
- libs/infinity_emb/infinity_emb/transformer/embedder/sentence_transformer.py
- libs/infinity_emb/infinity_emb/transformer/utils.py
- libs/infinity_emb/infinity_emb/transformer/utils_optimum.py
- libs/infinity_emb/tests/end_to_end/test_api_with_dummymodel.py
- libs/infinity_emb/tests/end_to_end/test_ct2_sentence.py
- libs/infinity_emb/tests/end_to_end/test_fastembed.py
- libs/infinity_emb/tests/end_to_end/test_optimum_embedding.py
- libs/infinity_emb/tests/end_to_end/test_sentence_transformers.py
- libs/infinity_emb/tests/unit_test/inference/test_batch_handler.py
- libs/infinity_emb/tests/unit_test/inference/test_models.py
- libs/infinity_emb/tests/unit_test/inference/test_select_model.py
- libs/infinity_emb/tests/unit_test/test_args.py
- libs/infinity_emb/tests/unit_test/test_engine.py
- libs/infinity_emb/tests/unit_test/transformer/classifier/test_torch_classifer.py
- libs/infinity_emb/tests/unit_test/transformer/crossencoder/test_optimum_crossencoder.py
- libs/infinity_emb/tests/unit_test/transformer/crossencoder/test_torch_crossencoder.py
- libs/infinity_emb/tests/unit_test/transformer/embedder/test_optimum.py
> expand: EngineArgs

- README.md
- docs/docs/benchmarking.md
- docs/docs/contribution.md
- docs/docs/deploy.md
- docs/docs/index.md
- docs/docs/integrations.md
- docs/docs/python_engine.md
- libs/infinity_emb/infinity_emb/fastapi_schemas/pymodels.py
- libs/infinity_emb/infinity_emb/infinity_server.py
- libs/infinity_emb/tests/end_to_end/test_api_with_dummymodel.py
- libs/infinity_emb/tests/end_to_end/test_ct2_sentence.py
- libs/infinity_emb/tests/end_to_end/test_fastembed.py
- libs/infinity_emb/tests/end_to_end/test_optimum_embedding.py
- libs/infinity_emb/tests/end_to_end/test_sentence_transformers.py
>  OpenAI models and update docs and

- libs/infinity_emb/poetry.lock
- libs/infinity_emb/pyproject.toml
Reverts michaelfeil/infinity#142
> Revert "Sentence transformers bump to 2.5.0"

- libs/infinity_emb/infinity_emb/engine.py
- libs/infinity_emb/infinity_emb/inference/batch_handler.py
- libs/infinity_emb/infinity_emb/primitives.py
Hi @michaelfeil, fixed some doc strings and type hints while perusing the source code :)
Let me know if that is in your interest
> Some docstring and typing fixes

- libs/infinity_emb/infinity_emb/args.py
- libs/infinity_emb/infinity_emb/infinity_server.py
> feat: add served_model_name argument for the infinity_server

- libs/infinity_emb/infinity_emb/transformer/acceleration.py
- libs/infinity_emb/infinity_emb/transformer/crossencoder/torch.py
- libs/infinity_emb/infinity_emb/transformer/embedder/sentence_transformer.py
This adds the fix for #155 to crossencoder as well as fixes some type hints
> update defered moving to cpu & type hints improvement

- libs/infinity_emb/Dockerfile
- libs/infinity_emb/infinity_emb/infinity_server.py
- enables offline running / pre-cache model
> update infinity offline solution

- libs/infinity_emb/tests/end_to_end/test_authentication.py
> Update tests for #287

- docs/benchmarks/benchmarking.md
- docs/benchmarks/simple_app.py
add `embed` to benchmarking scripts
> Benchmark update with `embed`

- infra/vast/README.md
> fixing link

- libs/infinity_emb/infinity_emb/transformer/vision/utils.py
Closes #367 
Closes #375 
@kimson99
> add verification check

- README.md
- libs/infinity_emb/infinity_emb/inference/batch_handler.py
- libs/infinity_emb/infinity_emb/transformer/audio/utils.py
- libs/infinity_emb/infinity_emb/transformer/vision/utils.py
> Update README. Extract audio related code into own utils

- docs/assets/create_openapi_with_server_hook.sh
- docs/docs/telemetry.md
- libs/client_infinity/run_generate_with_hook.sh
- libs/client_infinity/run_tests_with_hook.sh
- libs/infinity_emb/infinity_emb/engine.py
- libs/infinity_emb/infinity_emb/env.py
- libs/infinity_emb/infinity_emb/fastapi_schemas/docs.py
- libs/infinity_emb/infinity_emb/infinity_server.py
- libs/infinity_emb/infinity_emb/telemetry.py
> Add better start messages & telemetry documenation

- README.md
By submitting this PR, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/michaelfeil/infinity/blob/main/LICENSE).
> README: Add KubeAI under integrations

- .github/workflows/release_docker_container.yaml
Reverts michaelfeil/infinity#442
> Revert "Update release_docker_container.yaml"

- libs/client_infinity/infinity_client/pyproject.toml
> bump client version

- libs/infinity_emb/infinity_emb/transformer/vision/__init__.py
- libs/infinity_emb/infinity_emb/transformer/vision/torch_vision.py
Add any other context about the PR here.
> Add ColQwen2_5 to IMAGE_COL_MODELS

- docs/lm_head_to_classifier/convert_lm.py
Prevent special tokens from being added into yes no tokens, improve code readability
Add any other context about the PR here.
> Prevent special tokens from being added into yes no tokens, improve code readability
